In [1]:
import numpy as np
a=np.array([4,3,2,1])
print(a)
b=np.arange(10)
print(b)

[4 3 2 1]
[0 1 2 3 4 5 6 7 8 9]


In [2]:
a=range(10000)
%timeit [i**2 for i in a]

3.13 ms ± 524 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
a=np.arange(10000)
%timeit a**2
for i in a**2:
    print(i,end="")

8.94 µs ± 921 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
[       0        1        4 ... 99940009 99960004 99980001]
