In [3]:
import numpy as np
# array creation
a=np.array([1,2,3,4])
a
b=np.arange(10)
b


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
l=range(1000)
%timeit [i**2 for i in l]

260 µs ± 6.58 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
a=np.arange(1000)
%timeit a**2

1.33 µs ± 16.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [8]:
a.ndim
a.shape
len(a)

1000

In [10]:
a=np.array([1,2,3,4,5])
print('the_dimensions',a.ndim)
print("the_values",a.shape)
print('the_length',len(a))

the_dimensions 1
the_values (5,)
the_length 5


In [14]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a.ndim)
print(a.shape)
print(len(a))

2
(2, 4)
2


In [7]:
import numpy as np
a=np.array([[[1,2],[3,4]],[[4,5],[5,6]]])
print(a.ndim)
print(a.shape)
a

3
(2, 2, 2)


array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [5, 6]]])

In [9]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
a=np.zeros((3,3))
a=np.zeros(3)
a

array([0., 0., 0.])

In [12]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
a=np.diag([1,2,3,4])
a.T

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [16]:
a=np.random.rand(4)
a

array([0.78974994, 0.11137658, 0.86389907, 0.61773516])

In [17]:
a=np.random.randn(5)
a

array([-1.01230258, -0.65627874,  1.46649244, -0.37789051,  1.10522826])

In [18]:
a=np.array([[1,2,3,4],[6,4,3,2]])
a

array([[1, 2, 3, 4],
       [6, 4, 3, 2]])

In [21]:
a[1,2]=100
a

array([[  1,   2,   3,   4],
       [  6,   4, 100,   2]])

In [23]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
b=a[1:8]
np.shares_memory(a,b)

True

In [27]:
b[0]=20
print(a,b)

[ 1 20  3  4  5  6  7  8  9] [20  3  4  5  6  7  8]


In [30]:
print(id(a),id(b))

2142150364784 2141911530736


In [32]:
a=np.arange(1,10)
b=a
print(np.shares_memory(a,b),id(a),id(b))

True 2142150374768 2142150374768


In [33]:
c=a.copy()
print(np.shares_memory(a,b),np.shares_memory(a,c),id(a),id(b),id(c))

True False 2142150374768 2142150374768 2142150373520


In [39]:
a=np.random.randint(0,10,200)
a

array([8, 5, 9, 9, 9, 7, 3, 7, 6, 3, 0, 5, 6, 6, 6, 0, 4, 4, 6, 9, 2, 5,
       4, 9, 5, 6, 1, 2, 0, 9, 6, 0, 8, 2, 5, 4, 3, 7, 8, 2, 4, 8, 3, 5,
       5, 4, 2, 1, 1, 2, 4, 5, 8, 0, 0, 0, 3, 6, 8, 0, 7, 8, 2, 8, 4, 7,
       2, 3, 2, 4, 0, 1, 9, 4, 4, 1, 9, 5, 7, 0, 2, 3, 2, 1, 4, 1, 4, 6,
       8, 5, 4, 8, 1, 8, 9, 1, 4, 4, 2, 4, 8, 8, 4, 4, 8, 2, 6, 3, 8, 2,
       0, 4, 1, 8, 6, 3, 4, 2, 0, 3, 4, 6, 8, 0, 4, 7, 8, 8, 3, 0, 2, 9,
       0, 3, 5, 0, 6, 6, 6, 1, 1, 2, 3, 8, 1, 4, 3, 1, 3, 3, 4, 4, 1, 2,
       7, 0, 0, 7, 2, 4, 3, 4, 1, 0, 9, 6, 1, 3, 2, 7, 0, 2, 0, 2, 0, 5,
       8, 4, 8, 5, 3, 4, 0, 9, 9, 8, 8, 6, 9, 6, 5, 9, 3, 1, 8, 0, 5, 2,
       2, 2])

In [40]:
mask=a%2==0
a[mask]=-1
a

array([-1,  5,  9,  9,  9,  7,  3,  7, -1,  3, -1,  5, -1, -1, -1, -1, -1,
       -1, -1,  9, -1,  5, -1,  9,  5, -1,  1, -1, -1,  9, -1, -1, -1, -1,
        5, -1,  3,  7, -1, -1, -1, -1,  3,  5,  5, -1, -1,  1,  1, -1, -1,
        5, -1, -1, -1, -1,  3, -1, -1, -1,  7, -1, -1, -1, -1,  7, -1,  3,
       -1, -1, -1,  1,  9, -1, -1,  1,  9,  5,  7, -1, -1,  3, -1,  1, -1,
        1, -1, -1, -1,  5, -1, -1,  1, -1,  9,  1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1,  3, -1, -1, -1, -1,  1, -1, -1,  3, -1, -1, -1,
        3, -1, -1, -1, -1, -1,  7, -1, -1,  3, -1, -1,  9, -1,  3,  5, -1,
       -1, -1, -1,  1,  1, -1,  3, -1,  1, -1,  3,  1,  3,  3, -1, -1,  1,
       -1,  7, -1, -1,  7, -1, -1,  3, -1,  1, -1,  9, -1,  1,  3, -1,  7,
       -1, -1, -1, -1, -1,  5, -1, -1, -1,  5,  3, -1, -1,  9,  9, -1, -1,
       -1,  9, -1,  5,  9,  3,  1, -1, -1,  5, -1, -1, -1])

In [42]:
a=np.arange(1,20)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [49]:
a[[3]]

array([4])

In [50]:
a=np.arange(1,10)
a+1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
a**2

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [52]:
x=np.sum(a)
x

45

In [53]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
b=np.sum(1,axis=0)
b

1

In [55]:
data=np.loadtxt("populations.txt")
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])