In [1]:
import numpy as np
a=np.array([4,3,2,1])
print(a)
b=np.arange(10)
print(b)

[4 3 2 1]
[0 1 2 3 4 5 6 7 8 9]


In [2]:
a=range(10000)
%timeit [i**2 for i in a]

3.13 ms ± 524 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [8]:
a=np.array([1,2,3,4])
print(a.ndim)
print(a.shape)

1
(4,)


In [12]:
# multi dimensional array or 2dimension array
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a.ndim)
print(a.shape)


2
(2, 4)


In [15]:
# 3dimesional array
a=np.array([[[1,2],[3,4]],[[4,5],[6,7]]])
print(a.ndim)
print(a.shape)
print(len(a))

3
(2, 2, 2)
2


In [16]:
a=np.linspace(0,1,6)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [18]:
a=np.ones((3,3,))
print(a)
print(a.ndim)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
2


In [19]:
b=np.zeros((3,3))
print(b.ndim)

2


In [20]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
a=np.eye(3,2)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [22]:
a=np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [23]:
a=np.random.rand(4)
a

array([0.84103628, 0.24185488, 0.70522903, 0.60800859])

In [24]:
a=np.random.randn(4)
print(a)

[-0.29745313  1.29768618 -0.56840977  0.28646689]


In [26]:
a=np.arange(10)
print(a.dtype)

int32


In [29]:
a=np.arange(10,dtype="float64")
a.dtype

dtype('float64')

In [34]:
a=np.array([[1,2,2,3],[4,5,6,7]])
print(a[0,2])

2


In [35]:
a[0,3]=100
a


array([[  1,   2,   2, 100],
       [  4,   5,   6,   7]])

In [37]:
# slicing
a=np.arange(1,10)
a[1::]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
b=a[::]
print(np.shares_memory(a,b))
b[0]=100
print(a,b)
c=a[::].copy()
print(np.shares_memory(a,c))
c[0]=200
print(a,c)

True
[100   2   3   4   5   6   7   8   9] [100   2   3   4   5   6   7   8   9]
False
[100   2   3   4   5   6   7   8   9] [200   2   3   4   5   6   7   8   9]


In [43]:
a=np.arange(1,10)
mask=(a%2==0)
mask
a[mask]=-1
a

array([ 1, -1,  3, -1,  5, -1,  7, -1,  9])